version: 0.2

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing and configuring Rust."
      - curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
      - source "$HOME/.cargo/env"
      - rustup update
      - rustup target add wasm32-unknown-unknown
  build:
    on-failure: ABORT
    commands:
      - echo "Running tests."
      - cargo install trunk wasm-pack
      - trunk build
      - wasm-pack test --node